// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimerParcial.Data;

namespace PrimerParcial.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200602232906_suplidor-articulo")]
    partial class suplidorarticulo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrimerParcial.Models.Clasificaciones.ClasificacionArticulos", b =>
                {
                    b.Property<int>("idClasificacionArticulos")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoDeArticulos");

                    b.HasKey("idClasificacionArticulos");

                    b.ToTable("ClasificacionArticulos");
                });

            modelBuilder.Entity("PrimerParcial.Models.Clasificaciones.ClasificacionCliente", b =>
                {
                    b.Property<int>("idClasificacionCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoDeCliente");

                    b.HasKey("idClasificacionCliente");

                    b.ToTable("clasificacionClientes");
                });

            modelBuilder.Entity("PrimerParcial.Models.Clasificaciones.ClasificacionSuplidor", b =>
                {
                    b.Property<int>("idClasificacionSuplidor")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoDeSuplidor");

                    b.HasKey("idClasificacionSuplidor");

                    b.ToTable("ClasificacionSuplidor");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Articulo", b =>
                {
                    b.Property<int>("idArticulo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<string>("Nombre");

                    b.Property<int>("Precio");

                    b.Property<int>("idClasificacionArticulos");

                    b.Property<int>("idMarca");

                    b.Property<int>("idSuplidor");

                    b.HasKey("idArticulo");

                    b.HasIndex("idClasificacionArticulos");

                    b.HasIndex("idMarca");

                    b.HasIndex("idSuplidor");

                    b.ToTable("Articulo");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Ciudad", b =>
                {
                    b.Property<int>("idCiudad")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<int>("idPais");

                    b.Property<string>("nombre");

                    b.HasKey("idCiudad");

                    b.HasIndex("idPais");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion");

                    b.Property<int?>("DocumentoidTipoDeDocumento");

                    b.Property<string>("email");

                    b.Property<int>("idCiudad");

                    b.Property<int>("idClasificacionCliente");

                    b.Property<int>("idTipoDocumento");

                    b.Property<string>("nombre");

                    b.Property<string>("telefono");

                    b.HasKey("idCliente");

                    b.HasIndex("DocumentoidTipoDeDocumento");

                    b.HasIndex("idCiudad");

                    b.HasIndex("idClasificacionCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Marca", b =>
                {
                    b.Property<int>("idMarca")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.HasKey("idMarca");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Pais", b =>
                {
                    b.Property<int>("idPais")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("nombre");

                    b.HasKey("idPais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Suplidor", b =>
                {
                    b.Property<int>("idSuplidor")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email");

                    b.Property<int>("idCiudad");

                    b.Property<int>("idClasificacionSuplidor");

                    b.Property<string>("nombre");

                    b.Property<string>("telefono");

                    b.HasKey("idSuplidor");

                    b.HasIndex("idCiudad");

                    b.HasIndex("idClasificacionSuplidor");

                    b.ToTable("Suplidor");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.TipoDeDocumento", b =>
                {
                    b.Property<int>("idTipoDeDocumento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Documento");

                    b.Property<string>("Numero");

                    b.HasKey("idTipoDeDocumento");

                    b.ToTable("tipoDeDocumentos");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Articulo", b =>
                {
                    b.HasOne("PrimerParcial.Models.Clasificaciones.ClasificacionArticulos", "ClasificacionArticulos")
                        .WithMany()
                        .HasForeignKey("idClasificacionArticulos")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrimerParcial.Models.Entidades.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("idMarca")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrimerParcial.Models.Entidades.Suplidor", "Suplidor")
                        .WithMany()
                        .HasForeignKey("idSuplidor")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Ciudad", b =>
                {
                    b.HasOne("PrimerParcial.Models.Entidades.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("idPais")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Cliente", b =>
                {
                    b.HasOne("PrimerParcial.Models.Entidades.TipoDeDocumento", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoidTipoDeDocumento");

                    b.HasOne("PrimerParcial.Models.Entidades.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("idCiudad")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrimerParcial.Models.Clasificaciones.ClasificacionCliente", "clasificacionCliente")
                        .WithMany()
                        .HasForeignKey("idClasificacionCliente")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Suplidor", b =>
                {
                    b.HasOne("PrimerParcial.Models.Entidades.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("idCiudad")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrimerParcial.Models.Clasificaciones.ClasificacionSuplidor", "clasificacionSuplidor")
                        .WithMany()
                        .HasForeignKey("idClasificacionSuplidor")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
