// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimerParcial.Data;

namespace PrimerParcial.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200601220852_cliente")]
    partial class cliente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrimerParcial.Models.Clasificaciones.ClasificacionCliente", b =>
                {
                    b.Property<int>("idClasificacionCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoDeCliente");

                    b.HasKey("idClasificacionCliente");

                    b.ToTable("clasificacionClientes");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Ciudad", b =>
                {
                    b.Property<int>("idCiudad")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<int>("idPais");

                    b.Property<string>("nombre");

                    b.HasKey("idCiudad");

                    b.HasIndex("idPais");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion");

                    b.Property<int?>("DocumentoidTipoDeDocumento");

                    b.Property<string>("email");

                    b.Property<int>("idCiudad");

                    b.Property<int>("idClasificacionCliente");

                    b.Property<int>("idTipoDocumento");

                    b.Property<string>("nombre");

                    b.Property<string>("telefono");

                    b.HasKey("idCliente");

                    b.HasIndex("DocumentoidTipoDeDocumento");

                    b.HasIndex("idCiudad");

                    b.HasIndex("idClasificacionCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Pais", b =>
                {
                    b.Property<int>("idPais")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("nombre");

                    b.HasKey("idPais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.TipoDeDocumento", b =>
                {
                    b.Property<int>("idTipoDeDocumento")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Documento");

                    b.Property<string>("Numero");

                    b.HasKey("idTipoDeDocumento");

                    b.ToTable("tipoDeDocumentos");
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Ciudad", b =>
                {
                    b.HasOne("PrimerParcial.Models.Entidades.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("idPais")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrimerParcial.Models.Entidades.Cliente", b =>
                {
                    b.HasOne("PrimerParcial.Models.Entidades.TipoDeDocumento", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoidTipoDeDocumento");

                    b.HasOne("PrimerParcial.Models.Entidades.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("idCiudad")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrimerParcial.Models.Clasificaciones.ClasificacionCliente", "clasificacionCliente")
                        .WithMany()
                        .HasForeignKey("idClasificacionCliente")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
